<a href="https://colab.research.google.com/github/cybercolombia/suelosabio/blob/feature%2FSCRUM-13/notebooks/ClimatePipeline/01_ClimateDataDownloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ClimateDataDownloader

Descargador genérico de observaciones climáticas IDEAM publicadas mediante Socrata. Guarda datos crudos en Parquet particionado por variable, fuente, departamento, año y mes.

Este notebook **solo descarga y normaliza tipos básicos**. No suma, promedia ni audita las observaciones, porque esas reglas dependen de cada variable climática.

## 1. Configuración

### Uso rápido

1. Escoja un `DATASET_ID` y un `VARIABLE_NOMBRE`.
2. Configure uno o ambos departamentos permitidos.
3. Configure listas de años y meses. Para todos los meses use `list(range(1, 13))`; para enero a abril use `[1, 2, 3, 4]`.
4. Mantenga `SOBRESCRIBIR_PARQUET = False` para reanudar descargas existentes.
5. Cambie `EJECUTAR_DESCARGA = True` y ejecute el notebook completo.

Fuentes candidatas:

| Variable | Dataset ID |
|---|---|
| Temperatura ambiente | `sbwg-7ju4` |
| Temperatura mínima | `afdg-3zpb` |
| Temperatura máxima | `ccvq-rp9s` |
| Humedad del aire | `uext-mhny` |
| Precipitación | `s54a-sgyg` |
| Velocidad del viento | `sgfv-3yp8` |
| Presión atmosférica | `62tk-nxj5` |

In [1]:
from pathlib import Path

import pandas as pd
import requests

try:
    from IPython.display import Markdown, display
except ImportError:
    Markdown = str

    def display(valor):
        print(valor)

try:
    from google.colab import drive

    drive.mount('/content/drive')
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# Fuente a descargar. Cambiar ambos valores juntos.
DATASET_ID = '62tk-nxj5'
VARIABLE_NOMBRE = 'presion_atmosferica'

# Es obligatorio indicar uno o ambos departamentos del alcance.
DESCARGA_DEPARTAMENTOS = [
    'CUNDINAMARCA',
]

# Ejemplos: [2025], [2024, 2025] o list(range(2019, 2026)).
DESCARGA_ANIOS = [2024]

# Ejemplos: [1, 2, 3, 4] o list(range(1, 13)).
DESCARGA_MESES = list(range(1, 13))

DESCARGA_LIMIT = 1000
DESCARGA_MAX_LOTES = None
SOBRESCRIBIR_PARQUET = False
REQUEST_TIMEOUT = 180
REQUEST_REINTENTOS = 3
APP_TOKEN = None  # Opcional. No subir tokens reales al repositorio.

# Banderita de seguridad para Run all.
EJECUTAR_DESCARGA = True

PROCESSED_ROOT = (
    Path('/content/drive/MyDrive/eco2026_processed')
    if IN_COLAB
    else Path.cwd() / 'eco2026_processed'
)

print({
    'dataset_id': DATASET_ID,
    'variable': VARIABLE_NOMBRE,
    'departamentos': DESCARGA_DEPARTAMENTOS,
    'anios': DESCARGA_ANIOS,
    'meses': DESCARGA_MESES,
    'limit': DESCARGA_LIMIT,
    'max_lotes': DESCARGA_MAX_LOTES,
    'sobrescribir': SOBRESCRIBIR_PARQUET,
    'ejecutar': EJECUTAR_DESCARGA,
    'processed_root': str(PROCESSED_ROOT),
})

Mounted at /content/drive
{'dataset_id': '62tk-nxj5', 'variable': 'presion_atmosferica', 'departamentos': ['CUNDINAMARCA'], 'anios': [2024], 'meses': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12], 'limit': 1000, 'max_lotes': None, 'sobrescribir': False, 'ejecutar': True, 'processed_root': '/content/drive/MyDrive/eco2026_processed'}

## 2. Validación y plan de descarga

La configuración se valida antes de crear carpetas o consultar datos. Los departamentos se restringen al alcance aprobado: Boyacá y Cundinamarca.

In [2]:
import re
import unicodedata

DATASET_ID_PATTERN = re.compile(r'^[a-z0-9]{4}-[a-z0-9]{4}$', re.IGNORECASE)
DEPARTAMENTOS_PERMITIDOS = {'BOYACÁ', 'CUNDINAMARCA'}


def slugificar(valor):
    """Normaliza etiquetas para construir rutas deterministas."""
    texto = unicodedata.normalize('NFKD', str(valor))
    texto = texto.encode('ascii', errors='ignore').decode('ascii').lower()
    texto = re.sub(r'[^a-z0-9]+', '_', texto).strip('_')
    if not texto:
        raise ValueError(f'No se pudo construir una etiqueta de ruta para {valor!r}.')
    return texto


def unicos_ordenados(valores):
    return sorted(set(valores))


def validar_configuracion():
    if not DATASET_ID_PATTERN.fullmatch(str(DATASET_ID)):
        raise ValueError('DATASET_ID debe tener el formato xxxx-xxxx.')
    if not str(VARIABLE_NOMBRE).strip():
        raise ValueError('VARIABLE_NOMBRE es obligatorio.')
    if not DESCARGA_DEPARTAMENTOS:
        raise ValueError('Debe configurar al menos un departamento.')

    departamentos = unicos_ordenados(str(d).strip().upper() for d in DESCARGA_DEPARTAMENTOS)
    no_permitidos = set(departamentos) - DEPARTAMENTOS_PERMITIDOS
    if no_permitidos:
        raise ValueError(
            f'Departamentos fuera del alcance: {sorted(no_permitidos)}. '
            f'Permitidos: {sorted(DEPARTAMENTOS_PERMITIDOS)}.'
        )

    if not DESCARGA_ANIOS:
        raise ValueError('DESCARGA_ANIOS no puede estar vacío.')
    anios = unicos_ordenados(int(a) for a in DESCARGA_ANIOS)
    if any(a < 1900 or a > 2100 for a in anios):
        raise ValueError(f'Años fuera de rango: {anios}.')

    if not DESCARGA_MESES:
        raise ValueError('DESCARGA_MESES no puede estar vacío.')
    meses = unicos_ordenados(int(m) for m in DESCARGA_MESES)
    if any(m < 1 or m > 12 for m in meses):
        raise ValueError(f'Los meses deben estar entre 1 y 12: {meses}.')

    if int(DESCARGA_LIMIT) <= 0:
        raise ValueError('DESCARGA_LIMIT debe ser positivo.')
    if DESCARGA_MAX_LOTES is not None and int(DESCARGA_MAX_LOTES) <= 0:
        raise ValueError('DESCARGA_MAX_LOTES debe ser None o un entero positivo.')

    return departamentos, anios, meses


def construir_plan(departamentos, anios, meses):
    return [
        {'departamento': departamento, 'anio': anio, 'mes': mes}
        for departamento in departamentos
        for anio in anios
        for mes in meses
    ]

## 3. Acceso a Socrata

Las consultas usan `LIMIT` y `OFFSET` dentro de `$query`. Cada solicitud tiene reintentos para errores transitorios y mantiene un orden estable por fecha, estación, sensor e ID interno.

In [3]:
import time


def headers_socrata():
    headers = {'Accept': 'application/json', 'User-Agent': 'RAIZ-ClimateDataDownloader/1.0'}
    if APP_TOKEN:
        headers['X-App-Token'] = APP_TOKEN
    return headers


def consultar_metadata(dataset_id):
    url = f'https://www.datos.gov.co/api/views/{dataset_id}'
    response = requests.get(
        url,
        headers=headers_socrata(),
        timeout=REQUEST_TIMEOUT,
    )
    response.raise_for_status()
    return response.json()


def validar_esquema_ideam(metadata):
    campos = {columna.get('fieldName') for columna in metadata.get('columns', [])}
    obligatorios = {'departamento', 'fechaobservacion'}
    faltantes = obligatorios - campos
    if faltantes:
        raise ValueError(
            f'El dataset no tiene el esquema climático esperado. Faltan: {sorted(faltantes)}.'
        )
    return campos


def consultar_lote(dataset_id, where, limit, offset, order, timeout=REQUEST_TIMEOUT):
    url = f'https://www.datos.gov.co/resource/{dataset_id}.json'
    query = (
        f'SELECT * WHERE {where} ORDER BY {order} '
        f'LIMIT {int(limit)} OFFSET {int(offset)}'
    )

    ultimo_error = None
    for intento in range(1, REQUEST_REINTENTOS + 1):
        try:
            response = requests.get(
                url,
                params={'$query': query},
                headers=headers_socrata(),
                timeout=timeout,
            )
            response.raise_for_status()
            return pd.DataFrame(response.json())
        except requests.RequestException as exc:
            ultimo_error = exc
            if intento == REQUEST_REINTENTOS:
                break
            espera = min(2 ** (intento - 1), 30)
            print(
                f'Consulta falló en intento {intento}/{REQUEST_REINTENTOS}: {exc}. '
                f'Reintentando en {espera} s...'
            )
            time.sleep(espera)

    raise ultimo_error


def construir_orden(campos):
    candidatos = ['fechaobservacion', 'codigoestacion', 'codigosensor']
    presentes = [campo for campo in candidatos if campo in campos]
    presentes.append(':id')
    return ', '.join(presentes)

## 4. Particiones y reanudación

Cada lote de hasta 1.000 filas se guarda como un archivo `part-xxxxx.parquet`. Todos los archivos de un mismo departamento, año y mes quedan en la misma carpeta.

### `SOBRESCRIBIR_PARQUET = False`

Es el modo recomendado. Si existen partes consecutivas, la descarga empieza en el siguiente índice y usa el `OFFSET` correspondiente. Si la partición ya estaba completa, la API devolverá cero filas y no se escribirá nada nuevo.

Antes de reanudar se revisa el número de filas de cada archivo. Todas las partes salvo la última deben tener exactamente `DESCARGA_LIMIT` filas. Si el último archivo tiene menos, la partición se considera completa. Esto también evita reanudar accidentalmente con un `LIMIT` diferente al usado en la primera corrida.

### `SOBRESCRIBIR_PARQUET = True`

La descarga vuelve a empezar en el lote cero y reemplaza archivos con el mismo nombre. No crea deliberadamente otra carpeta. Tampoco elimina partes antiguas sobrantes; por eso no se recomienda salvo que se entienda el estado de la partición.

`mkdir(..., exist_ok=True)` reutiliza la ruta montada. Si Google Drive muestra dos carpetas visualmente iguales, suele indicar rutas raíz distintas, accesos directos duplicados o diferencias invisibles en el nombre; no es efecto directo de esta bandera.

In [4]:
from datetime import datetime

PART_PATTERN = re.compile(r'^part-(\d{5})\.parquet$')


def inicio_mes_siguiente(anio, mes):
    if mes == 12:
        return anio + 1, 1
    return anio, mes + 1


def ruta_particion(variable, dataset_id, departamento, anio, mes):
    return (
        PROCESSED_ROOT
        / 'clima_crudo'
        / f'variable={slugificar(variable)}'
        / f'fuente={dataset_id.lower()}'
        / f'departamento={slugificar(departamento)}'
        / f'anio={int(anio)}'
        / f'mes={int(mes):02d}'
    )


def partes_existentes(output_dir):
    encontrados = []
    for archivo in output_dir.glob('part-*.parquet'):
        coincidencia = PART_PATTERN.fullmatch(archivo.name)
        if coincidencia:
            encontrados.append((int(coincidencia.group(1)), archivo))
    encontrados.sort(key=lambda item: item[0])
    return encontrados


def validar_secuencia_partes(partes):
    indices = [indice for indice, _ in partes]
    if not indices:
        return
    esperados = list(range(indices[-1] + 1))
    if indices != esperados:
        faltantes = sorted(set(esperados) - set(indices))
        raise RuntimeError(
            f'La partición tiene huecos en sus archivos: {faltantes}. '
            'No se reanuda para evitar saltar registros.'
        )


def validar_filas_partes(partes, limit):
    if not partes:
        return [], False

    try:
        import pyarrow.parquet as pq
    except ImportError as exc:
        raise ImportError('Se necesita pyarrow para validar los Parquet existentes.') from exc

    filas = [pq.ParquetFile(archivo).metadata.num_rows for _, archivo in partes]
    inconsistentes = [
        indice
        for (indice, _), filas_archivo in zip(partes[:-1], filas[:-1])
        if filas_archivo != int(limit)
    ]
    if inconsistentes:
        raise RuntimeError(
            f'Las partes {inconsistentes} no tienen DESCARGA_LIMIT={limit} filas. '
            'No es seguro calcular el OFFSET para reanudar.'
        )
    if filas[-1] > int(limit):
        raise RuntimeError(
            f'La última parte tiene {filas[-1]} filas, más que el limit={limit}.'
        )

    particion_completa = filas[-1] < int(limit)
    return filas, particion_completa


def normalizar_lote(df, dataset_id, variable):
    df = df.copy()
    if 'fechaobservacion' in df.columns:
        df['fechaobservacion'] = pd.to_datetime(df['fechaobservacion'], errors='coerce')
    for columna in ['valorobservado', 'latitud', 'longitud']:
        if columna in df.columns:
            df[columna] = pd.to_numeric(df[columna], errors='coerce')
    df['dataset_id'] = dataset_id
    df['variable_fuente'] = slugificar(variable)
    return df


def descargar_particion(
    dataset_id,
    variable,
    departamento,
    anio,
    mes,
    campos,
    limit=1000,
    max_lotes=None,
    sobrescribir=False,
):
    output_dir = ruta_particion(variable, dataset_id, departamento, anio, mes)
    output_dir.mkdir(parents=True, exist_ok=True)

    existentes = partes_existentes(output_dir)
    validar_secuencia_partes(existentes)
    filas_existentes, ya_completa = validar_filas_partes(existentes, limit)
    inicio_idx = 0 if sobrescribir else len(existentes)
    lote_idx = inicio_idx
    offset = lote_idx * int(limit)
    lotes_consultados = 0
    filas_nuevas = 0
    detalle = []
    inicio_tiempo = time.perf_counter()

    anio_fin, mes_fin = inicio_mes_siguiente(anio, mes)
    fecha_inicio = f'{int(anio):04d}-{int(mes):02d}-01T00:00:00'
    fecha_fin = f'{anio_fin:04d}-{mes_fin:02d}-01T00:00:00'
    departamento_sql = str(departamento).replace("'", "''")
    where = (
        f"departamento = '{departamento_sql}' "
        f"AND fechaobservacion >= '{fecha_inicio}' "
        f"AND fechaobservacion < '{fecha_fin}'"
    )
    order = construir_orden(campos)

    print(f'Carpeta: {output_dir}')
    print(f'Partes existentes: {len(existentes):,}')
    if filas_existentes:
        print(f'Filas por parte existente: {filas_existentes[:10]}')
    print(f'Inicio lote={lote_idx:,} | offset={offset:,} | sobrescribir={sobrescribir}')

    if ya_completa and not sobrescribir:
        print('La última parte tiene menos filas que el limit; la partición ya está completa.')
        resumen = {
            'dataset_id': dataset_id,
            'variable': slugificar(variable),
            'departamento': departamento,
            'anio': int(anio),
            'mes': int(mes),
            'estado': 'ya_completa',
            'partes_existentes_inicio': len(existentes),
            'partes_escritas_corrida': 0,
            'filas_corrida': 0,
            'duracion_segundos': round(time.perf_counter() - inicio_tiempo, 2),
            'carpeta': str(output_dir),
        }
        return resumen, pd.DataFrame()

    estado_particion = 'completa'
    ultimo_lote_escrito = None

    while True:
        if max_lotes is not None and lotes_consultados >= max_lotes:
            estado_particion = 'pausada_por_max_lotes'
            print(f'Corte por max_lotes={max_lotes}.')
            break

        reloj_inicio = datetime.now()
        lote_tiempo = time.perf_counter()
        print(
            f'Consultando lote {lote_idx:,} | offset={offset:,} | '
            f'limit={int(limit):,} | inicio={reloj_inicio:%H:%M:%S}'
        )
        df_lote = consultar_lote(
            dataset_id=dataset_id,
            where=where,
            limit=limit,
            offset=offset,
            order=order,
        )
        lotes_consultados += 1

        if df_lote.empty:
            print('La API no devolvió más filas para esta partición.')
            break

        df_lote = normalizar_lote(df_lote, dataset_id, variable)
        output_path = output_dir / f'part-{lote_idx:05d}.parquet'
        ya_existia = output_path.exists()
        df_lote.to_parquet(output_path, index=False)

        filas_lote = len(df_lote)
        filas_nuevas += filas_lote
        ultimo_lote_escrito = lote_idx
        reloj_fin = datetime.now()
        duracion_lote = round(time.perf_counter() - lote_tiempo, 2)
        print(
            f'Guardado {output_path.name} | filas={filas_lote:,} | '
            f'duración={duracion_lote:.2f} s | fin={reloj_fin:%H:%M:%S}'
        )

        detalle.append({
            'departamento': departamento,
            'anio': int(anio),
            'mes': int(mes),
            'lote': lote_idx,
            'offset': offset,
            'filas': filas_lote,
            'estado': 'sobrescrito' if ya_existia else 'escrito',
            'inicio': reloj_inicio.isoformat(timespec='seconds'),
            'fin': reloj_fin.isoformat(timespec='seconds'),
            'duracion_segundos': duracion_lote,
            'archivo': str(output_path),
        })

        if filas_lote < limit:
            print(f'Último lote detectado con {filas_lote:,} filas.')
            break

        lote_idx += 1
        offset += int(limit)

    if sobrescribir and existentes and ultimo_lote_escrito is not None:
        sobrantes = [indice for indice, _ in existentes if indice > ultimo_lote_escrito]
        if sobrantes:
            print(
                'ADVERTENCIA: quedaron partes antiguas con índices mayores al último '
                f'lote escrito: {sobrantes[:10]}.'
            )

    resumen = {
        'dataset_id': dataset_id,
        'variable': slugificar(variable),
        'departamento': departamento,
        'anio': int(anio),
        'mes': int(mes),
        'estado': estado_particion,
        'partes_existentes_inicio': len(existentes),
        'partes_escritas_corrida': len(detalle),
        'filas_corrida': filas_nuevas,
        'duracion_segundos': round(time.perf_counter() - inicio_tiempo, 2),
        'carpeta': str(output_dir),
    }
    return resumen, pd.DataFrame(detalle)

## 5. Ejecución

El plan recorre todas las combinaciones configuradas. Un error en una partición queda registrado y no borra las partes descargadas anteriormente.

In [5]:
resumen_particiones = pd.DataFrame()
detalle_lotes = pd.DataFrame()

departamentos, anios, meses = validar_configuracion()
plan_descarga = construir_plan(departamentos, anios, meses)
vista_plan = pd.DataFrame(plan_descarga)
vista_plan['carpeta'] = vista_plan.apply(
    lambda fila: str(
        ruta_particion(
            VARIABLE_NOMBRE,
            DATASET_ID,
            fila['departamento'],
            fila['anio'],
            fila['mes'],
        )
    ),
    axis=1,
)
display(Markdown(f'## Plan configurado — {len(plan_descarga)} particiones'))
display(vista_plan)

if not EJECUTAR_DESCARGA:
    print('Descarga desactivada. Revise la configuración y cambie EJECUTAR_DESCARGA a True.')
else:
    try:
        import pyarrow  # noqa: F401
    except ImportError as exc:
        raise ImportError('Para guardar Parquet instale pyarrow: !pip install pyarrow') from exc

    metadata = consultar_metadata(DATASET_ID)
    campos_dataset = validar_esquema_ideam(metadata)

    print(f"Dataset: {metadata.get('name')} ({DATASET_ID})")
    print(f'Variable de salida: {slugificar(VARIABLE_NOMBRE)}')
    print(f'Particiones a procesar: {len(plan_descarga):,}')
    print(f'Ruta raíz: {PROCESSED_ROOT / "clima_crudo"}')

    resumenes = []
    detalles = []

    for indice, item in enumerate(plan_descarga, start=1):
        titulo = (
            f"➡️ Partición {indice}/{len(plan_descarga)} — "
            f"{item['departamento']} | {item['anio']}-{item['mes']:02d}"
        )
        display(Markdown(f'---\n\n## {titulo}'))

        try:
            resumen, detalle = descargar_particion(
                dataset_id=DATASET_ID,
                variable=VARIABLE_NOMBRE,
                departamento=item['departamento'],
                anio=item['anio'],
                mes=item['mes'],
                campos=campos_dataset,
                limit=DESCARGA_LIMIT,
                max_lotes=DESCARGA_MAX_LOTES,
                sobrescribir=SOBRESCRIBIR_PARQUET,
            )
            resumenes.append(resumen)
            if not detalle.empty:
                detalles.append(detalle)
        except Exception as exc:
            print(f'ERROR en partición: {type(exc).__name__}: {exc}')
            resumenes.append({
                'dataset_id': DATASET_ID,
                'variable': slugificar(VARIABLE_NOMBRE),
                **item,
                'estado': 'error',
                'error': f'{type(exc).__name__}: {exc}',
            })

    resumen_particiones = pd.DataFrame(resumenes)
    detalle_lotes = pd.concat(detalles, ignore_index=True) if detalles else pd.DataFrame()

    display(Markdown('---\n\n## Resumen final'))
    display(resumen_particiones)
    display(detalle_lotes)

## Plan configurado — 12 particiones

    departamento  anio  mes                                            carpeta
0   CUNDINAMARCA  2024    1  /content/drive/MyDrive/eco2026_processed/clima...
1   CUNDINAMARCA  2024    2  /content/drive/MyDrive/eco2026_processed/clima...
2   CUNDINAMARCA  2024    3  /content/drive/MyDrive/eco2026_processed/clima...
3   CUNDINAMARCA  2024    4  /content/drive/MyDrive/eco2026_processed/clima...
4   CUNDINAMARCA  2024    5  /content/drive/MyDrive/eco2026_processed/clima...
5   CUNDINAMARCA  2024    6  /content/drive/MyDrive/eco2026_processed/clima...
6   CUNDINAMARCA  2024    7  /content/drive/MyDrive/eco2026_processed/clima...
7   CUNDINAMARCA  2024    8  /content/drive/MyDrive/eco2026_processed/clima...
8   CUNDINAMARCA  2024    9  /content/drive/MyDrive/eco2026_processed/clima...
9   CUNDINAMARCA  2024   10  /content/drive/MyDrive/eco2026_processed/clima...
10  CUNDINAMARCA  2024   11  /content/drive/MyDrive/eco2026_processed/clima...
11  CUNDINAMARCA  2024   12  /content/drive/MyDrive/eco2026_processed/clima...

Dataset: Presión Atmosférica (62tk-nxj5)
Variable de salida: presion_atmosferica
Particiones a procesar: 12
Ruta raíz: /content/drive/MyDrive/eco2026_processed/clima_crudo

---

## ➡️ Partición 1/12 — CUNDINAMARCA | 2024-01

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=01
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:11:31
Guardado part-00000.parquet | filas=1,000 | duración=0.62 s | fin=04:11:31
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:11:31
Guardado part-00001.parquet | filas=1,000 | duración=0.55 s | fin=04:11:32
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:11:32
Guardado part-00002.parquet | filas=1,000 | duración=0.53 s | fin=04:11:32
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:11:32
Guardado part-00003.parquet | filas=1,000 | duración=0.62 s | fin=04:11:33
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:11:33
Guardado part-00004.parquet | filas=1,000 | duración=0.47 s | fin=04:11:34
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:11:34
Guardado part-00005.parquet | filas=1,000 | duración=0.50 s | fin=04:11:34
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:11:34
Guardado part-00006.parquet | filas=1,000 | duración=0.61 s | fin=04:11:35
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:11:35
Guardado part-00007.parquet | filas=1,000 | duración=0.47 s | fin=04:11:35
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:11:35
Guardado part-00008.parquet | filas=1,000 | duración=0.66 s | fin=04:11:36
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:11:36
Guardado part-00009.parquet | filas=1,000 | duración=0.48 s | fin=04:11:36
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:11:36
Guardado part-00010.parquet | filas=1,000 | duración=0.50 s | fin=04:11:37
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:11:37
Guardado part-00011.parquet | filas=1,000 | duración=0.49 s | fin=04:11:37
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:11:37
Guardado part-00012.parquet | filas=1,000 | duración=0.82 s | fin=04:11:38
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:11:38
Guardado part-00013.parquet | filas=1,000 | duración=0.56 s | fin=04:11:39
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:11:39
Guardado part-00014.parquet | filas=1,000 | duración=0.52 s | fin=04:11:39
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:11:39
Guardado part-00015.parquet | filas=1,000 | duración=0.58 s | fin=04:11:40
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:11:40
Guardado part-00016.parquet | filas=1,000 | duración=0.71 s | fin=04:11:40
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:11:40
Guardado part-00017.parquet | filas=1,000 | duración=0.70 s | fin=04:11:41
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:11:41
Guardado part-00018.parquet | filas=1,000 | duración=0.55 s | fin=04:11:42
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:11:42
Guardado part-00019.parquet | filas=1,000 | duración=0.63 s | fin=04:11:42
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:11:42
Guardado part-00020.parquet | filas=1,000 | duración=0.57 s | fin=04:11:43
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:11:43
Guardado part-00021.parquet | filas=1,000 | duración=0.68 s | fin=04:11:44
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:11:44
Guardado part-00022.parquet | filas=1,000 | duración=0.85 s | fin=04:11:44
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:11:44
Guardado part-00023.parquet | filas=1,000 | duración=0.64 s | fin=04:11:45
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:11:45
Guardado part-00024.parquet | filas=1,000 | duración=0.73 s | fin=04:11:46
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:11:46
Guardado part-00025.parquet | filas=1,000 | duración=0.56 s | fin=04:11:46
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:11:46
Guardado part-00026.parquet | filas=1,000 | duración=0.53 s | fin=04:11:47
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:11:47
Guardado part-00027.parquet | filas=1,000 | duración=0.72 s | fin=04:11:48
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:11:48
Guardado part-00028.parquet | filas=1,000 | duración=0.60 s | fin=04:11:48
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:11:48
Guardado part-00029.parquet | filas=1,000 | duración=0.65 s | fin=04:11:49
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:11:49
Guardado part-00030.parquet | filas=1,000 | duración=0.63 s | fin=04:11:50
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:11:50
Guardado part-00031.parquet | filas=1,000 | duración=0.67 s | fin=04:11:50
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:11:50
Guardado part-00032.parquet | filas=1,000 | duración=0.62 s | fin=04:11:51
Consultando lote 33 | offset=33,000 | limit=1,000 | inicio=04:11:51
Guardado part-00033.parquet | filas=1,000 | duración=0.71 s | fin=04:11:52
Consultando lote 34 | offset=34,000 | limit=1,000 | inicio=04:11:52
Guardado part-00034.parquet | filas=1,000 | duración=0.67 s | fin=04:11:52
Consultando lote 35 | offset=35,000 | limit=1,000 | inicio=04:11:52
Guardado part-00035.parquet | filas=811 | duración=0.76 s | fin=04:11:53
Último lote detectado con 811 filas.

---

## ➡️ Partición 2/12 — CUNDINAMARCA | 2024-02

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=02
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:11:53
Guardado part-00000.parquet | filas=1,000 | duración=0.79 s | fin=04:11:54
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:11:54
Guardado part-00001.parquet | filas=1,000 | duración=0.72 s | fin=04:11:54
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:11:54
Guardado part-00002.parquet | filas=1,000 | duración=0.67 s | fin=04:11:55
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:11:55
Guardado part-00003.parquet | filas=1,000 | duración=0.50 s | fin=04:11:56
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:11:56
Guardado part-00004.parquet | filas=1,000 | duración=0.45 s | fin=04:11:56
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:11:56
Guardado part-00005.parquet | filas=1,000 | duración=0.51 s | fin=04:11:57
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:11:57
Guardado part-00006.parquet | filas=1,000 | duración=0.48 s | fin=04:11:57
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:11:57
Guardado part-00007.parquet | filas=1,000 | duración=0.75 s | fin=04:11:58
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:11:58
Guardado part-00008.parquet | filas=1,000 | duración=0.52 s | fin=04:11:58
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:11:58
Guardado part-00009.parquet | filas=1,000 | duración=0.57 s | fin=04:11:59
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:11:59
Guardado part-00010.parquet | filas=1,000 | duración=0.57 s | fin=04:12:00
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:12:00
Guardado part-00011.parquet | filas=1,000 | duración=0.58 s | fin=04:12:00
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:12:00
Guardado part-00012.parquet | filas=1,000 | duración=0.69 s | fin=04:12:01
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:12:01
Guardado part-00013.parquet | filas=1,000 | duración=0.57 s | fin=04:12:01
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:12:01
Guardado part-00014.parquet | filas=1,000 | duración=0.92 s | fin=04:12:02
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:12:02
Guardado part-00015.parquet | filas=1,000 | duración=0.53 s | fin=04:12:03
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:12:03
Guardado part-00016.parquet | filas=1,000 | duración=0.53 s | fin=04:12:03
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:12:03
Guardado part-00017.parquet | filas=1,000 | duración=0.67 s | fin=04:12:04
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:12:04
Guardado part-00018.parquet | filas=1,000 | duración=0.80 s | fin=04:12:05
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:12:05
Guardado part-00019.parquet | filas=1,000 | duración=0.75 s | fin=04:12:06
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:12:06
Guardado part-00020.parquet | filas=1,000 | duración=0.67 s | fin=04:12:06
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:12:06
Guardado part-00021.parquet | filas=924 | duración=0.69 s | fin=04:12:07
Último lote detectado con 924 filas.

---

## ➡️ Partición 3/12 — CUNDINAMARCA | 2024-03

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=03
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:12:07
Guardado part-00000.parquet | filas=1,000 | duración=0.53 s | fin=04:12:07
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:12:07
Guardado part-00001.parquet | filas=1,000 | duración=0.58 s | fin=04:12:08
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:12:08
Guardado part-00002.parquet | filas=1,000 | duración=0.48 s | fin=04:12:09
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:12:09
Guardado part-00003.parquet | filas=1,000 | duración=0.51 s | fin=04:12:09
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:12:09
Guardado part-00004.parquet | filas=1,000 | duración=0.62 s | fin=04:12:10
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:12:10
Guardado part-00005.parquet | filas=1,000 | duración=0.54 s | fin=04:12:10
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:12:10
Guardado part-00006.parquet | filas=1,000 | duración=0.59 s | fin=04:12:11
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:12:11
Guardado part-00007.parquet | filas=1,000 | duración=0.72 s | fin=04:12:12
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:12:12
Guardado part-00008.parquet | filas=1,000 | duración=0.59 s | fin=04:12:12
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:12:12
Guardado part-00009.parquet | filas=1,000 | duración=0.58 s | fin=04:12:13
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:12:13
Guardado part-00010.parquet | filas=1,000 | duración=0.57 s | fin=04:12:13
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:12:13
Guardado part-00011.parquet | filas=1,000 | duración=0.52 s | fin=04:12:14
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:12:14
Guardado part-00012.parquet | filas=1,000 | duración=0.58 s | fin=04:12:14
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:12:14
Guardado part-00013.parquet | filas=1,000 | duración=0.58 s | fin=04:12:15
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:12:15
Guardado part-00014.parquet | filas=1,000 | duración=0.56 s | fin=04:12:15
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:12:15
Guardado part-00015.parquet | filas=1,000 | duración=0.60 s | fin=04:12:16
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:12:16
Guardado part-00016.parquet | filas=1,000 | duración=0.68 s | fin=04:12:17
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:12:17
Guardado part-00017.parquet | filas=1,000 | duración=0.57 s | fin=04:12:17
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:12:17
Guardado part-00018.parquet | filas=1,000 | duración=0.67 s | fin=04:12:18
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:12:18
Guardado part-00019.parquet | filas=670 | duración=0.55 s | fin=04:12:19
Último lote detectado con 670 filas.

---

## ➡️ Partición 4/12 — CUNDINAMARCA | 2024-04

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=04
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:12:19
Guardado part-00000.parquet | filas=1,000 | duración=0.58 s | fin=04:12:19
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:12:19
Guardado part-00001.parquet | filas=1,000 | duración=0.51 s | fin=04:12:20
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:12:20
Guardado part-00002.parquet | filas=1,000 | duración=0.54 s | fin=04:12:20
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:12:20
Guardado part-00003.parquet | filas=1,000 | duración=0.63 s | fin=04:12:21
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:12:21
Guardado part-00004.parquet | filas=1,000 | duración=0.64 s | fin=04:12:21
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:12:21
Guardado part-00005.parquet | filas=1,000 | duración=0.63 s | fin=04:12:22
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:12:22
Guardado part-00006.parquet | filas=1,000 | duración=0.59 s | fin=04:12:23
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:12:23
Guardado part-00007.parquet | filas=1,000 | duración=0.63 s | fin=04:12:23
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:12:23
Guardado part-00008.parquet | filas=1,000 | duración=0.63 s | fin=04:12:24
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:12:24
Guardado part-00009.parquet | filas=1,000 | duración=0.54 s | fin=04:12:24
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:12:24
Guardado part-00010.parquet | filas=1,000 | duración=0.63 s | fin=04:12:25
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:12:25
Guardado part-00011.parquet | filas=1,000 | duración=0.67 s | fin=04:12:26
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:12:26
Guardado part-00012.parquet | filas=1,000 | duración=3.84 s | fin=04:12:30
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:12:30
Guardado part-00013.parquet | filas=1,000 | duración=0.69 s | fin=04:12:30
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:12:30
Guardado part-00014.parquet | filas=1,000 | duración=0.59 s | fin=04:12:31
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:12:31
Guardado part-00015.parquet | filas=830 | duración=0.65 s | fin=04:12:32
Último lote detectado con 830 filas.

---

## ➡️ Partición 5/12 — CUNDINAMARCA | 2024-05

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=05
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:12:32
Guardado part-00000.parquet | filas=1,000 | duración=0.48 s | fin=04:12:32
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:12:32
Guardado part-00001.parquet | filas=1,000 | duración=0.56 s | fin=04:12:33
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:12:33
Guardado part-00002.parquet | filas=1,000 | duración=0.50 s | fin=04:12:33
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:12:33
Guardado part-00003.parquet | filas=1,000 | duración=0.55 s | fin=04:12:34
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:12:34
Guardado part-00004.parquet | filas=1,000 | duración=0.51 s | fin=04:12:34
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:12:34
Guardado part-00005.parquet | filas=1,000 | duración=0.61 s | fin=04:12:35
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:12:35
Guardado part-00006.parquet | filas=1,000 | duración=0.59 s | fin=04:12:35
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:12:35
Guardado part-00007.parquet | filas=1,000 | duración=0.75 s | fin=04:12:36
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:12:36
Guardado part-00008.parquet | filas=1,000 | duración=0.60 s | fin=04:12:37
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:12:37
Guardado part-00009.parquet | filas=1,000 | duración=0.60 s | fin=04:12:37
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:12:37
Guardado part-00010.parquet | filas=1,000 | duración=0.76 s | fin=04:12:38
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:12:38
Guardado part-00011.parquet | filas=1,000 | duración=0.63 s | fin=04:12:39
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:12:39
Guardado part-00012.parquet | filas=1,000 | duración=0.73 s | fin=04:12:39
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:12:39
Guardado part-00013.parquet | filas=1,000 | duración=0.64 s | fin=04:12:40
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:12:40
Guardado part-00014.parquet | filas=1,000 | duración=0.63 s | fin=04:12:41
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:12:41
Guardado part-00015.parquet | filas=1,000 | duración=0.64 s | fin=04:12:41
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:12:41
Guardado part-00016.parquet | filas=1,000 | duración=0.75 s | fin=04:12:42
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:12:42
Guardado part-00017.parquet | filas=1,000 | duración=0.72 s | fin=04:12:43
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:12:43
Guardado part-00018.parquet | filas=1,000 | duración=0.70 s | fin=04:12:44
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:12:44
Guardado part-00019.parquet | filas=410 | duración=0.67 s | fin=04:12:44
Último lote detectado con 410 filas.

---

## ➡️ Partición 6/12 — CUNDINAMARCA | 2024-06

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=06
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:12:44
Guardado part-00000.parquet | filas=1,000 | duración=0.49 s | fin=04:12:45
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:12:45
Guardado part-00001.parquet | filas=1,000 | duración=0.56 s | fin=04:12:45
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:12:45
Guardado part-00002.parquet | filas=1,000 | duración=0.60 s | fin=04:12:46
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:12:46
Guardado part-00003.parquet | filas=1,000 | duración=0.54 s | fin=04:12:46
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:12:46
Guardado part-00004.parquet | filas=1,000 | duración=0.50 s | fin=04:12:47
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:12:47
Guardado part-00005.parquet | filas=1,000 | duración=0.66 s | fin=04:12:48
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:12:48
Guardado part-00006.parquet | filas=1,000 | duración=0.65 s | fin=04:12:48
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:12:48
Guardado part-00007.parquet | filas=1,000 | duración=0.69 s | fin=04:12:49
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:12:49
Guardado part-00008.parquet | filas=1,000 | duración=0.52 s | fin=04:12:49
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:12:49
Guardado part-00009.parquet | filas=1,000 | duración=0.60 s | fin=04:12:50
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:12:50
Guardado part-00010.parquet | filas=1,000 | duración=0.60 s | fin=04:12:51
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:12:51
Guardado part-00011.parquet | filas=1,000 | duración=0.69 s | fin=04:12:51
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:12:51
Guardado part-00012.parquet | filas=1,000 | duración=0.54 s | fin=04:12:52
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:12:52
Guardado part-00013.parquet | filas=1,000 | duración=0.67 s | fin=04:12:53
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:12:53
Guardado part-00014.parquet | filas=1,000 | duración=0.66 s | fin=04:12:53
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:12:53
Guardado part-00015.parquet | filas=1,000 | duración=0.64 s | fin=04:12:54
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:12:54
Guardado part-00016.parquet | filas=1,000 | duración=0.63 s | fin=04:12:54
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:12:54
Guardado part-00017.parquet | filas=1,000 | duración=0.70 s | fin=04:12:55
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:12:55
Guardado part-00018.parquet | filas=1,000 | duración=0.63 s | fin=04:12:56
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:12:56
Guardado part-00019.parquet | filas=1,000 | duración=0.63 s | fin=04:12:56
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:12:56
Guardado part-00020.parquet | filas=1,000 | duración=0.66 s | fin=04:12:57
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:12:57
Guardado part-00021.parquet | filas=983 | duración=0.61 s | fin=04:12:58
Último lote detectado con 983 filas.

---

## ➡️ Partición 7/12 — CUNDINAMARCA | 2024-07

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=07
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:12:58
Guardado part-00000.parquet | filas=1,000 | duración=0.57 s | fin=04:12:58
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:12:58
Guardado part-00001.parquet | filas=1,000 | duración=0.55 s | fin=04:12:59
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:12:59
Guardado part-00002.parquet | filas=1,000 | duración=0.70 s | fin=04:13:00
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:13:00
Guardado part-00003.parquet | filas=1,000 | duración=0.77 s | fin=04:13:00
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:13:00
Guardado part-00004.parquet | filas=1,000 | duración=1.06 s | fin=04:13:01
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:13:01
Guardado part-00005.parquet | filas=1,000 | duración=1.25 s | fin=04:13:03
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:13:03
Guardado part-00006.parquet | filas=1,000 | duración=0.69 s | fin=04:13:03
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:13:03
Guardado part-00007.parquet | filas=1,000 | duración=0.56 s | fin=04:13:04
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:13:04
Guardado part-00008.parquet | filas=1,000 | duración=0.58 s | fin=04:13:04
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:13:04
Guardado part-00009.parquet | filas=1,000 | duración=0.61 s | fin=04:13:05
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:13:05
Guardado part-00010.parquet | filas=1,000 | duración=0.71 s | fin=04:13:06
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:13:06
Guardado part-00011.parquet | filas=1,000 | duración=0.62 s | fin=04:13:06
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:13:06
Guardado part-00012.parquet | filas=1,000 | duración=0.59 s | fin=04:13:07
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:13:07
Guardado part-00013.parquet | filas=1,000 | duración=0.57 s | fin=04:13:08
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:13:08
Guardado part-00014.parquet | filas=1,000 | duración=0.68 s | fin=04:13:08
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:13:08
Guardado part-00015.parquet | filas=1,000 | duración=0.57 s | fin=04:13:09
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:13:09
Guardado part-00016.parquet | filas=1,000 | duración=0.61 s | fin=04:13:09
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:13:09
Guardado part-00017.parquet | filas=1,000 | duración=0.63 s | fin=04:13:10
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:13:10
Guardado part-00018.parquet | filas=1,000 | duración=0.71 s | fin=04:13:11
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:13:11
Guardado part-00019.parquet | filas=1,000 | duración=0.75 s | fin=04:13:12
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:13:12
Guardado part-00020.parquet | filas=1,000 | duración=0.64 s | fin=04:13:12
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:13:12
Guardado part-00021.parquet | filas=1,000 | duración=0.70 s | fin=04:13:13
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:13:13
Guardado part-00022.parquet | filas=1,000 | duración=0.67 s | fin=04:13:14
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:13:14
Guardado part-00023.parquet | filas=966 | duración=0.64 s | fin=04:13:14
Último lote detectado con 966 filas.

---

## ➡️ Partición 8/12 — CUNDINAMARCA | 2024-08

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=08
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:13:14
Guardado part-00000.parquet | filas=1,000 | duración=0.47 s | fin=04:13:15
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:13:15
Guardado part-00001.parquet | filas=1,000 | duración=0.54 s | fin=04:13:15
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:13:15
Guardado part-00002.parquet | filas=1,000 | duración=0.45 s | fin=04:13:16
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:13:16
Guardado part-00003.parquet | filas=1,000 | duración=0.51 s | fin=04:13:16
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:13:16
Guardado part-00004.parquet | filas=1,000 | duración=0.61 s | fin=04:13:17
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:13:17
Guardado part-00005.parquet | filas=1,000 | duración=0.65 s | fin=04:13:17
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:13:17
Guardado part-00006.parquet | filas=1,000 | duración=0.50 s | fin=04:13:18
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:13:18
Guardado part-00007.parquet | filas=1,000 | duración=0.51 s | fin=04:13:18
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:13:18
Guardado part-00008.parquet | filas=1,000 | duración=0.59 s | fin=04:13:19
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:13:19
Guardado part-00009.parquet | filas=1,000 | duración=0.61 s | fin=04:13:20
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:13:20
Guardado part-00010.parquet | filas=1,000 | duración=0.82 s | fin=04:13:20
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:13:20
Guardado part-00011.parquet | filas=1,000 | duración=0.67 s | fin=04:13:21
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:13:21
Guardado part-00012.parquet | filas=1,000 | duración=0.56 s | fin=04:13:22
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:13:22
Guardado part-00013.parquet | filas=1,000 | duración=0.64 s | fin=04:13:22
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:13:22
Guardado part-00014.parquet | filas=1,000 | duración=0.66 s | fin=04:13:23
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:13:23
Guardado part-00015.parquet | filas=1,000 | duración=0.59 s | fin=04:13:24
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:13:24
Guardado part-00016.parquet | filas=1,000 | duración=0.66 s | fin=04:13:24
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:13:24
Guardado part-00017.parquet | filas=1,000 | duración=0.84 s | fin=04:13:25
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:13:25
Guardado part-00018.parquet | filas=1,000 | duración=0.57 s | fin=04:13:26
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:13:26
Guardado part-00019.parquet | filas=1,000 | duración=0.67 s | fin=04:13:26
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:13:26
Guardado part-00020.parquet | filas=1,000 | duración=0.68 s | fin=04:13:27
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:13:27
Guardado part-00021.parquet | filas=1,000 | duración=0.64 s | fin=04:13:28
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:13:28
Guardado part-00022.parquet | filas=1,000 | duración=0.67 s | fin=04:13:28
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:13:28
Guardado part-00023.parquet | filas=1,000 | duración=0.66 s | fin=04:13:29
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:13:29
Guardado part-00024.parquet | filas=1,000 | duración=0.87 s | fin=04:13:30
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:13:30
Guardado part-00025.parquet | filas=1,000 | duración=0.78 s | fin=04:13:31
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:13:31
Guardado part-00026.parquet | filas=1,000 | duración=0.67 s | fin=04:13:31
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:13:31
Guardado part-00027.parquet | filas=1,000 | duración=0.63 s | fin=04:13:32
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:13:32
Guardado part-00028.parquet | filas=1,000 | duración=0.71 s | fin=04:13:33
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:13:33
Guardado part-00029.parquet | filas=1,000 | duración=0.62 s | fin=04:13:33
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:13:33
Guardado part-00030.parquet | filas=1,000 | duración=0.74 s | fin=04:13:34
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:13:34
Guardado part-00031.parquet | filas=1,000 | duración=0.79 s | fin=04:13:35
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:13:35
Guardado part-00032.parquet | filas=1,000 | duración=0.64 s | fin=04:13:35
Consultando lote 33 | offset=33,000 | limit=1,000 | inicio=04:13:35
Guardado part-00033.parquet | filas=1,000 | duración=0.69 s | fin=04:13:36
Consultando lote 34 | offset=34,000 | limit=1,000 | inicio=04:13:36
Guardado part-00034.parquet | filas=1,000 | duración=0.75 s | fin=04:13:37
Consultando lote 35 | offset=35,000 | limit=1,000 | inicio=04:13:37
Guardado part-00035.parquet | filas=1,000 | duración=0.70 s | fin=04:13:38
Consultando lote 36 | offset=36,000 | limit=1,000 | inicio=04:13:38
Guardado part-00036.parquet | filas=1,000 | duración=0.69 s | fin=04:13:38
Consultando lote 37 | offset=37,000 | limit=1,000 | inicio=04:13:38
Guardado part-00037.parquet | filas=1,000 | duración=0.75 s | fin=04:13:39
Consultando lote 38 | offset=38,000 | limit=1,000 | inicio=04:13:39
Guardado part-00038.parquet | filas=1,000 | duración=0.72 s | fin=04:13:40
Consultando lote 39 | offset=39,000 | limit=1,000 | inicio=04:13:40
Guardado part-00039.parquet | filas=1,000 | duración=0.87 s | fin=04:13:41
Consultando lote 40 | offset=40,000 | limit=1,000 | inicio=04:13:41
Guardado part-00040.parquet | filas=1,000 | duración=0.68 s | fin=04:13:41
Consultando lote 41 | offset=41,000 | limit=1,000 | inicio=04:13:41
Guardado part-00041.parquet | filas=1,000 | duración=0.72 s | fin=04:13:42
Consultando lote 42 | offset=42,000 | limit=1,000 | inicio=04:13:42
Guardado part-00042.parquet | filas=574 | duración=0.72 s | fin=04:13:43
Último lote detectado con 574 filas.

---

## ➡️ Partición 9/12 — CUNDINAMARCA | 2024-09

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=09
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:13:43
Guardado part-00000.parquet | filas=1,000 | duración=0.48 s | fin=04:13:43
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:13:43
Guardado part-00001.parquet | filas=1,000 | duración=0.59 s | fin=04:13:44
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:13:44
Guardado part-00002.parquet | filas=1,000 | duración=0.53 s | fin=04:13:44
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:13:44
Guardado part-00003.parquet | filas=1,000 | duración=0.45 s | fin=04:13:45
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:13:45
Guardado part-00004.parquet | filas=1,000 | duración=0.53 s | fin=04:13:45
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:13:45
Guardado part-00005.parquet | filas=1,000 | duración=0.61 s | fin=04:13:46
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:13:46
Guardado part-00006.parquet | filas=1,000 | duración=0.57 s | fin=04:13:46
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:13:46
Guardado part-00007.parquet | filas=1,000 | duración=0.53 s | fin=04:13:47
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:13:47
Guardado part-00008.parquet | filas=1,000 | duración=0.50 s | fin=04:13:48
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:13:48
Guardado part-00009.parquet | filas=1,000 | duración=0.55 s | fin=04:13:48
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:13:48
Guardado part-00010.parquet | filas=1,000 | duración=0.52 s | fin=04:13:49
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:13:49
Guardado part-00011.parquet | filas=1,000 | duración=0.55 s | fin=04:13:49
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:13:49
Guardado part-00012.parquet | filas=1,000 | duración=0.59 s | fin=04:13:50
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:13:50
Guardado part-00013.parquet | filas=1,000 | duración=0.54 s | fin=04:13:50
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:13:50
Guardado part-00014.parquet | filas=1,000 | duración=0.54 s | fin=04:13:51
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:13:51
Guardado part-00015.parquet | filas=1,000 | duración=0.59 s | fin=04:13:51
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:13:51
Guardado part-00016.parquet | filas=1,000 | duración=0.57 s | fin=04:13:52
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:13:52
Guardado part-00017.parquet | filas=1,000 | duración=0.71 s | fin=04:13:53
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:13:53
Guardado part-00018.parquet | filas=1,000 | duración=0.57 s | fin=04:13:53
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:13:53
Guardado part-00019.parquet | filas=1,000 | duración=0.64 s | fin=04:13:54
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:13:54
Guardado part-00020.parquet | filas=1,000 | duración=0.63 s | fin=04:13:55
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:13:55
Guardado part-00021.parquet | filas=1,000 | duración=0.65 s | fin=04:13:55
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:13:55
Guardado part-00022.parquet | filas=1,000 | duración=0.65 s | fin=04:13:56
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:13:56
Guardado part-00023.parquet | filas=1,000 | duración=0.67 s | fin=04:13:57
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:13:57
Guardado part-00024.parquet | filas=1,000 | duración=0.62 s | fin=04:13:57
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:13:57
Guardado part-00025.parquet | filas=1,000 | duración=0.65 s | fin=04:13:58
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:13:58
Guardado part-00026.parquet | filas=1,000 | duración=0.63 s | fin=04:13:58
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:13:58
Guardado part-00027.parquet | filas=1,000 | duración=0.76 s | fin=04:13:59
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:13:59
Guardado part-00028.parquet | filas=1,000 | duración=0.79 s | fin=04:14:00
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:14:00
Guardado part-00029.parquet | filas=1,000 | duración=0.68 s | fin=04:14:01
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:14:01
Guardado part-00030.parquet | filas=1,000 | duración=0.82 s | fin=04:14:01
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:14:01
Guardado part-00031.parquet | filas=1,000 | duración=1.35 s | fin=04:14:03
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:14:03
Guardado part-00032.parquet | filas=53 | duración=0.77 s | fin=04:14:04
Último lote detectado con 53 filas.

---

## ➡️ Partición 10/12 — CUNDINAMARCA | 2024-10

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=10
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:14:04
Guardado part-00000.parquet | filas=1,000 | duración=0.67 s | fin=04:14:04
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:14:04
Guardado part-00001.parquet | filas=1,000 | duración=0.48 s | fin=04:14:05
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:14:05
Guardado part-00002.parquet | filas=1,000 | duración=0.50 s | fin=04:14:05
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:14:05
Guardado part-00003.parquet | filas=1,000 | duración=0.55 s | fin=04:14:06
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:14:06
Guardado part-00004.parquet | filas=1,000 | duración=0.48 s | fin=04:14:06
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:14:06
Guardado part-00005.parquet | filas=1,000 | duración=0.49 s | fin=04:14:07
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:14:07
Guardado part-00006.parquet | filas=1,000 | duración=0.62 s | fin=04:14:07
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:14:07
Guardado part-00007.parquet | filas=1,000 | duración=0.54 s | fin=04:14:08
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:14:08
Guardado part-00008.parquet | filas=1,000 | duración=0.55 s | fin=04:14:08
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:14:08
Guardado part-00009.parquet | filas=1,000 | duración=0.48 s | fin=04:14:09
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:14:09
Guardado part-00010.parquet | filas=1,000 | duración=0.77 s | fin=04:14:10
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:14:10
Guardado part-00011.parquet | filas=1,000 | duración=0.53 s | fin=04:14:10
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:14:10
Guardado part-00012.parquet | filas=1,000 | duración=1.10 s | fin=04:14:11
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:14:11
Guardado part-00013.parquet | filas=1,000 | duración=0.66 s | fin=04:14:12
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:14:12
Guardado part-00014.parquet | filas=1,000 | duración=0.71 s | fin=04:14:13
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:14:13
Guardado part-00015.parquet | filas=1,000 | duración=0.50 s | fin=04:14:13
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:14:13
Guardado part-00016.parquet | filas=1,000 | duración=0.61 s | fin=04:14:14
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:14:14
Guardado part-00017.parquet | filas=1,000 | duración=0.57 s | fin=04:14:14
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:14:14
Guardado part-00018.parquet | filas=1,000 | duración=0.55 s | fin=04:14:15
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:14:15
Guardado part-00019.parquet | filas=1,000 | duración=0.72 s | fin=04:14:16
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:14:16
Guardado part-00020.parquet | filas=1,000 | duración=0.60 s | fin=04:14:16
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:14:16
Guardado part-00021.parquet | filas=1,000 | duración=0.62 s | fin=04:14:17
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:14:17
Guardado part-00022.parquet | filas=1,000 | duración=0.71 s | fin=04:14:18
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:14:18
Guardado part-00023.parquet | filas=1,000 | duración=0.74 s | fin=04:14:18
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:14:18
Guardado part-00024.parquet | filas=1,000 | duración=0.65 s | fin=04:14:19
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:14:19
Guardado part-00025.parquet | filas=1,000 | duración=0.67 s | fin=04:14:20
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:14:20
Guardado part-00026.parquet | filas=1,000 | duración=0.66 s | fin=04:14:20
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:14:20
Guardado part-00027.parquet | filas=1,000 | duración=0.74 s | fin=04:14:21
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:14:21
Guardado part-00028.parquet | filas=1,000 | duración=0.76 s | fin=04:14:22
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:14:22
Guardado part-00029.parquet | filas=1,000 | duración=0.64 s | fin=04:14:22
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:14:22
Guardado part-00030.parquet | filas=1,000 | duración=0.73 s | fin=04:14:23
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:14:23
Guardado part-00031.parquet | filas=1,000 | duración=0.65 s | fin=04:14:24
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:14:24
Guardado part-00032.parquet | filas=1,000 | duración=0.76 s | fin=04:14:25
Consultando lote 33 | offset=33,000 | limit=1,000 | inicio=04:14:25
Guardado part-00033.parquet | filas=1,000 | duración=0.83 s | fin=04:14:25
Consultando lote 34 | offset=34,000 | limit=1,000 | inicio=04:14:25
Guardado part-00034.parquet | filas=1,000 | duración=0.68 s | fin=04:14:26
Consultando lote 35 | offset=35,000 | limit=1,000 | inicio=04:14:26
Guardado part-00035.parquet | filas=1,000 | duración=0.87 s | fin=04:14:27
Consultando lote 36 | offset=36,000 | limit=1,000 | inicio=04:14:27
Guardado part-00036.parquet | filas=1,000 | duración=0.72 s | fin=04:14:28
Consultando lote 37 | offset=37,000 | limit=1,000 | inicio=04:14:28
Guardado part-00037.parquet | filas=1,000 | duración=0.78 s | fin=04:14:29
Consultando lote 38 | offset=38,000 | limit=1,000 | inicio=04:14:29
Guardado part-00038.parquet | filas=1,000 | duración=0.78 s | fin=04:14:29
Consultando lote 39 | offset=39,000 | limit=1,000 | inicio=04:14:29
Guardado part-00039.parquet | filas=1,000 | duración=0.89 s | fin=04:14:30
Consultando lote 40 | offset=40,000 | limit=1,000 | inicio=04:14:30
Guardado part-00040.parquet | filas=1,000 | duración=0.74 s | fin=04:14:31
Consultando lote 41 | offset=41,000 | limit=1,000 | inicio=04:14:31
Guardado part-00041.parquet | filas=1,000 | duración=0.87 s | fin=04:14:32
Consultando lote 42 | offset=42,000 | limit=1,000 | inicio=04:14:32
Guardado part-00042.parquet | filas=1,000 | duración=0.82 s | fin=04:14:33
Consultando lote 43 | offset=43,000 | limit=1,000 | inicio=04:14:33
Guardado part-00043.parquet | filas=1,000 | duración=1.00 s | fin=04:14:34
Consultando lote 44 | offset=44,000 | limit=1,000 | inicio=04:14:34
Guardado part-00044.parquet | filas=1,000 | duración=0.87 s | fin=04:14:34
Consultando lote 45 | offset=45,000 | limit=1,000 | inicio=04:14:34
Guardado part-00045.parquet | filas=1,000 | duración=0.82 s | fin=04:14:35
Consultando lote 46 | offset=46,000 | limit=1,000 | inicio=04:14:35
Guardado part-00046.parquet | filas=1,000 | duración=0.96 s | fin=04:14:36
Consultando lote 47 | offset=47,000 | limit=1,000 | inicio=04:14:36
Guardado part-00047.parquet | filas=1,000 | duración=0.94 s | fin=04:14:37
Consultando lote 48 | offset=48,000 | limit=1,000 | inicio=04:14:37
Guardado part-00048.parquet | filas=1,000 | duración=0.90 s | fin=04:14:38
Consultando lote 49 | offset=49,000 | limit=1,000 | inicio=04:14:38
Guardado part-00049.parquet | filas=1,000 | duración=0.86 s | fin=04:14:39
Consultando lote 50 | offset=50,000 | limit=1,000 | inicio=04:14:39
Guardado part-00050.parquet | filas=1,000 | duración=1.04 s | fin=04:14:40
Consultando lote 51 | offset=51,000 | limit=1,000 | inicio=04:14:40
Guardado part-00051.parquet | filas=1,000 | duración=0.87 s | fin=04:14:41
Consultando lote 52 | offset=52,000 | limit=1,000 | inicio=04:14:41
Guardado part-00052.parquet | filas=1,000 | duración=0.85 s | fin=04:14:42
Consultando lote 53 | offset=53,000 | limit=1,000 | inicio=04:14:42
Guardado part-00053.parquet | filas=1,000 | duración=0.87 s | fin=04:14:43
Consultando lote 54 | offset=54,000 | limit=1,000 | inicio=04:14:43
Guardado part-00054.parquet | filas=1,000 | duración=0.87 s | fin=04:14:43
Consultando lote 55 | offset=55,000 | limit=1,000 | inicio=04:14:43
Guardado part-00055.parquet | filas=1,000 | duración=0.86 s | fin=04:14:44
Consultando lote 56 | offset=56,000 | limit=1,000 | inicio=04:14:44
Guardado part-00056.parquet | filas=1,000 | duración=1.06 s | fin=04:14:45
Consultando lote 57 | offset=57,000 | limit=1,000 | inicio=04:14:45
Guardado part-00057.parquet | filas=1,000 | duración=0.92 s | fin=04:14:46
Consultando lote 58 | offset=58,000 | limit=1,000 | inicio=04:14:46
Guardado part-00058.parquet | filas=1,000 | duración=0.88 s | fin=04:14:47
Consultando lote 59 | offset=59,000 | limit=1,000 | inicio=04:14:47
Guardado part-00059.parquet | filas=1,000 | duración=0.96 s | fin=04:14:48
Consultando lote 60 | offset=60,000 | limit=1,000 | inicio=04:14:48
Guardado part-00060.parquet | filas=1,000 | duración=1.00 s | fin=04:14:49
Consultando lote 61 | offset=61,000 | limit=1,000 | inicio=04:14:49
Guardado part-00061.parquet | filas=1,000 | duración=0.92 s | fin=04:14:50
Consultando lote 62 | offset=62,000 | limit=1,000 | inicio=04:14:50
Guardado part-00062.parquet | filas=1,000 | duración=1.15 s | fin=04:14:51
Consultando lote 63 | offset=63,000 | limit=1,000 | inicio=04:14:51
Guardado part-00063.parquet | filas=1,000 | duración=1.10 s | fin=04:14:52
Consultando lote 64 | offset=64,000 | limit=1,000 | inicio=04:14:52
Guardado part-00064.parquet | filas=1,000 | duración=1.01 s | fin=04:14:53
Consultando lote 65 | offset=65,000 | limit=1,000 | inicio=04:14:53
Guardado part-00065.parquet | filas=417 | duración=0.92 s | fin=04:14:54
Último lote detectado con 417 filas.

---

## ➡️ Partición 11/12 — CUNDINAMARCA | 2024-11

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=11
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:14:54
Guardado part-00000.parquet | filas=1,000 | duración=0.51 s | fin=04:14:55
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:14:55
Guardado part-00001.parquet | filas=1,000 | duración=0.52 s | fin=04:14:55
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:14:55
Guardado part-00002.parquet | filas=1,000 | duración=0.58 s | fin=04:14:56
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:14:56
Guardado part-00003.parquet | filas=1,000 | duración=0.80 s | fin=04:14:57
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:14:57
Guardado part-00004.parquet | filas=1,000 | duración=0.58 s | fin=04:14:57
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:14:57
Guardado part-00005.parquet | filas=1,000 | duración=0.59 s | fin=04:14:58
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:14:58
Guardado part-00006.parquet | filas=1,000 | duración=0.77 s | fin=04:14:59
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:14:59
Guardado part-00007.parquet | filas=1,000 | duración=0.67 s | fin=04:14:59
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:14:59
Guardado part-00008.parquet | filas=1,000 | duración=0.72 s | fin=04:15:00
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:15:00
Guardado part-00009.parquet | filas=1,000 | duración=0.75 s | fin=04:15:01
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:15:01
Guardado part-00010.parquet | filas=1,000 | duración=0.72 s | fin=04:15:01
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:15:01
Guardado part-00011.parquet | filas=1,000 | duración=0.79 s | fin=04:15:02
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:15:02
Guardado part-00012.parquet | filas=1,000 | duración=1.14 s | fin=04:15:03
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:15:03
Guardado part-00013.parquet | filas=1,000 | duración=0.84 s | fin=04:15:04
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:15:04
Guardado part-00014.parquet | filas=1,000 | duración=0.69 s | fin=04:15:05
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:15:05
Guardado part-00015.parquet | filas=1,000 | duración=0.75 s | fin=04:15:06
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:15:06
Guardado part-00016.parquet | filas=1,000 | duración=0.64 s | fin=04:15:06
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:15:06
Guardado part-00017.parquet | filas=1,000 | duración=0.78 s | fin=04:15:07
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:15:07
Guardado part-00018.parquet | filas=1,000 | duración=0.60 s | fin=04:15:08
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:15:08
Guardado part-00019.parquet | filas=1,000 | duración=0.72 s | fin=04:15:08
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:15:08
Guardado part-00020.parquet | filas=1,000 | duración=0.70 s | fin=04:15:09
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:15:09
Guardado part-00021.parquet | filas=1,000 | duración=0.69 s | fin=04:15:10
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:15:10
Guardado part-00022.parquet | filas=1,000 | duración=0.68 s | fin=04:15:11
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:15:11
Guardado part-00023.parquet | filas=1,000 | duración=0.78 s | fin=04:15:11
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:15:11
Guardado part-00024.parquet | filas=1,000 | duración=0.76 s | fin=04:15:12
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:15:12
Guardado part-00025.parquet | filas=1,000 | duración=0.84 s | fin=04:15:13
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:15:13
Guardado part-00026.parquet | filas=1,000 | duración=0.73 s | fin=04:15:14
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:15:14
Guardado part-00027.parquet | filas=1,000 | duración=0.79 s | fin=04:15:14
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:15:14
Guardado part-00028.parquet | filas=1,000 | duración=0.74 s | fin=04:15:15
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:15:15
Guardado part-00029.parquet | filas=1,000 | duración=0.81 s | fin=04:15:16
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:15:16
Guardado part-00030.parquet | filas=1,000 | duración=0.92 s | fin=04:15:17
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:15:17
Guardado part-00031.parquet | filas=1,000 | duración=0.81 s | fin=04:15:18
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:15:18
Guardado part-00032.parquet | filas=1,000 | duración=1.00 s | fin=04:15:19
Consultando lote 33 | offset=33,000 | limit=1,000 | inicio=04:15:19
Guardado part-00033.parquet | filas=1,000 | duración=0.80 s | fin=04:15:19
Consultando lote 34 | offset=34,000 | limit=1,000 | inicio=04:15:19
Guardado part-00034.parquet | filas=1,000 | duración=0.95 s | fin=04:15:20
Consultando lote 35 | offset=35,000 | limit=1,000 | inicio=04:15:20
Guardado part-00035.parquet | filas=1,000 | duración=0.98 s | fin=04:15:21
Consultando lote 36 | offset=36,000 | limit=1,000 | inicio=04:15:21
Guardado part-00036.parquet | filas=1,000 | duración=0.95 s | fin=04:15:22
Consultando lote 37 | offset=37,000 | limit=1,000 | inicio=04:15:22
Guardado part-00037.parquet | filas=1,000 | duración=0.86 s | fin=04:15:23
Consultando lote 38 | offset=38,000 | limit=1,000 | inicio=04:15:23
Guardado part-00038.parquet | filas=1,000 | duración=0.86 s | fin=04:15:24
Consultando lote 39 | offset=39,000 | limit=1,000 | inicio=04:15:24
Guardado part-00039.parquet | filas=1,000 | duración=1.05 s | fin=04:15:25
Consultando lote 40 | offset=40,000 | limit=1,000 | inicio=04:15:25
Guardado part-00040.parquet | filas=1,000 | duración=0.93 s | fin=04:15:26
Consultando lote 41 | offset=41,000 | limit=1,000 | inicio=04:15:26
Guardado part-00041.parquet | filas=1,000 | duración=0.97 s | fin=04:15:27
Consultando lote 42 | offset=42,000 | limit=1,000 | inicio=04:15:27
Guardado part-00042.parquet | filas=1,000 | duración=1.09 s | fin=04:15:28
Consultando lote 43 | offset=43,000 | limit=1,000 | inicio=04:15:28
Guardado part-00043.parquet | filas=1,000 | duración=0.93 s | fin=04:15:29
Consultando lote 44 | offset=44,000 | limit=1,000 | inicio=04:15:29
Guardado part-00044.parquet | filas=1,000 | duración=0.90 s | fin=04:15:30
Consultando lote 45 | offset=45,000 | limit=1,000 | inicio=04:15:30
Guardado part-00045.parquet | filas=1,000 | duración=1.15 s | fin=04:15:31
Consultando lote 46 | offset=46,000 | limit=1,000 | inicio=04:15:31
Guardado part-00046.parquet | filas=1,000 | duración=1.00 s | fin=04:15:32
Consultando lote 47 | offset=47,000 | limit=1,000 | inicio=04:15:32
Guardado part-00047.parquet | filas=1,000 | duración=0.96 s | fin=04:15:33
Consultando lote 48 | offset=48,000 | limit=1,000 | inicio=04:15:33
Guardado part-00048.parquet | filas=1,000 | duración=1.02 s | fin=04:15:34
Consultando lote 49 | offset=49,000 | limit=1,000 | inicio=04:15:34
Guardado part-00049.parquet | filas=1,000 | duración=0.99 s | fin=04:15:35
Consultando lote 50 | offset=50,000 | limit=1,000 | inicio=04:15:35
Guardado part-00050.parquet | filas=1,000 | duración=1.22 s | fin=04:15:36
Consultando lote 51 | offset=51,000 | limit=1,000 | inicio=04:15:36
Guardado part-00051.parquet | filas=1,000 | duración=1.04 s | fin=04:15:37
Consultando lote 52 | offset=52,000 | limit=1,000 | inicio=04:15:37
Guardado part-00052.parquet | filas=1,000 | duración=1.01 s | fin=04:15:38
Consultando lote 53 | offset=53,000 | limit=1,000 | inicio=04:15:38
Guardado part-00053.parquet | filas=1,000 | duración=1.07 s | fin=04:15:39
Consultando lote 54 | offset=54,000 | limit=1,000 | inicio=04:15:39
Guardado part-00054.parquet | filas=1,000 | duración=1.26 s | fin=04:15:41
Consultando lote 55 | offset=55,000 | limit=1,000 | inicio=04:15:41
Guardado part-00055.parquet | filas=1,000 | duración=1.21 s | fin=04:15:42
Consultando lote 56 | offset=56,000 | limit=1,000 | inicio=04:15:42
Guardado part-00056.parquet | filas=1,000 | duración=1.01 s | fin=04:15:43
Consultando lote 57 | offset=57,000 | limit=1,000 | inicio=04:15:43
Guardado part-00057.parquet | filas=1,000 | duración=1.09 s | fin=04:15:44
Consultando lote 58 | offset=58,000 | limit=1,000 | inicio=04:15:44
Guardado part-00058.parquet | filas=1,000 | duración=1.12 s | fin=04:15:45
Consultando lote 59 | offset=59,000 | limit=1,000 | inicio=04:15:45
Guardado part-00059.parquet | filas=1,000 | duración=1.05 s | fin=04:15:46
Consultando lote 60 | offset=60,000 | limit=1,000 | inicio=04:15:46
Guardado part-00060.parquet | filas=1,000 | duración=1.12 s | fin=04:15:47
Consultando lote 61 | offset=61,000 | limit=1,000 | inicio=04:15:47
Guardado part-00061.parquet | filas=1,000 | duración=1.14 s | fin=04:15:48
Consultando lote 62 | offset=62,000 | limit=1,000 | inicio=04:15:48
Guardado part-00062.parquet | filas=1,000 | duración=1.10 s | fin=04:15:50
Consultando lote 63 | offset=63,000 | limit=1,000 | inicio=04:15:50
Guardado part-00063.parquet | filas=1,000 | duración=1.16 s | fin=04:15:51
Consultando lote 64 | offset=64,000 | limit=1,000 | inicio=04:15:51
Guardado part-00064.parquet | filas=1,000 | duración=1.13 s | fin=04:15:52
Consultando lote 65 | offset=65,000 | limit=1,000 | inicio=04:15:52
Guardado part-00065.parquet | filas=1,000 | duración=1.28 s | fin=04:15:53
Consultando lote 66 | offset=66,000 | limit=1,000 | inicio=04:15:53
Guardado part-00066.parquet | filas=1,000 | duración=1.09 s | fin=04:15:54
Consultando lote 67 | offset=67,000 | limit=1,000 | inicio=04:15:54
Guardado part-00067.parquet | filas=1,000 | duración=1.04 s | fin=04:15:55
Consultando lote 68 | offset=68,000 | limit=1,000 | inicio=04:15:55
Guardado part-00068.parquet | filas=1,000 | duración=1.26 s | fin=04:15:56
Consultando lote 69 | offset=69,000 | limit=1,000 | inicio=04:15:56
Guardado part-00069.parquet | filas=1,000 | duración=1.14 s | fin=04:15:58
Consultando lote 70 | offset=70,000 | limit=1,000 | inicio=04:15:58
Guardado part-00070.parquet | filas=1,000 | duración=1.13 s | fin=04:15:59
Consultando lote 71 | offset=71,000 | limit=1,000 | inicio=04:15:59
Guardado part-00071.parquet | filas=788 | duración=1.06 s | fin=04:16:00
Último lote detectado con 788 filas.

---

## ➡️ Partición 12/12 — CUNDINAMARCA | 2024-12

Carpeta: /content/drive/MyDrive/eco2026_processed/clima_crudo/variable=presion_atmosferica/fuente=62tk-nxj5/departamento=cundinamarca/anio=2024/mes=12
Partes existentes: 0
Inicio lote=0 | offset=0 | sobrescribir=False
Consultando lote 0 | offset=0 | limit=1,000 | inicio=04:16:00
Guardado part-00000.parquet | filas=1,000 | duración=0.55 s | fin=04:16:00
Consultando lote 1 | offset=1,000 | limit=1,000 | inicio=04:16:00
Guardado part-00001.parquet | filas=1,000 | duración=0.59 s | fin=04:16:01
Consultando lote 2 | offset=2,000 | limit=1,000 | inicio=04:16:01
Guardado part-00002.parquet | filas=1,000 | duración=0.59 s | fin=04:16:02
Consultando lote 3 | offset=3,000 | limit=1,000 | inicio=04:16:02
Guardado part-00003.parquet | filas=1,000 | duración=0.58 s | fin=04:16:02
Consultando lote 4 | offset=4,000 | limit=1,000 | inicio=04:16:02
Guardado part-00004.parquet | filas=1,000 | duración=0.75 s | fin=04:16:03
Consultando lote 5 | offset=5,000 | limit=1,000 | inicio=04:16:03
Guardado part-00005.parquet | filas=1,000 | duración=0.80 s | fin=04:16:04
Consultando lote 6 | offset=6,000 | limit=1,000 | inicio=04:16:04
Guardado part-00006.parquet | filas=1,000 | duración=0.62 s | fin=04:16:04
Consultando lote 7 | offset=7,000 | limit=1,000 | inicio=04:16:04
Guardado part-00007.parquet | filas=1,000 | duración=0.61 s | fin=04:16:05
Consultando lote 8 | offset=8,000 | limit=1,000 | inicio=04:16:05
Guardado part-00008.parquet | filas=1,000 | duración=0.53 s | fin=04:16:05
Consultando lote 9 | offset=9,000 | limit=1,000 | inicio=04:16:05
Guardado part-00009.parquet | filas=1,000 | duración=0.76 s | fin=04:16:06
Consultando lote 10 | offset=10,000 | limit=1,000 | inicio=04:16:06
Guardado part-00010.parquet | filas=1,000 | duración=0.74 s | fin=04:16:07
Consultando lote 11 | offset=11,000 | limit=1,000 | inicio=04:16:07
Guardado part-00011.parquet | filas=1,000 | duración=0.69 s | fin=04:16:08
Consultando lote 12 | offset=12,000 | limit=1,000 | inicio=04:16:08
Guardado part-00012.parquet | filas=1,000 | duración=0.85 s | fin=04:16:09
Consultando lote 13 | offset=13,000 | limit=1,000 | inicio=04:16:09
Guardado part-00013.parquet | filas=1,000 | duración=0.65 s | fin=04:16:09
Consultando lote 14 | offset=14,000 | limit=1,000 | inicio=04:16:09
Guardado part-00014.parquet | filas=1,000 | duración=0.69 s | fin=04:16:10
Consultando lote 15 | offset=15,000 | limit=1,000 | inicio=04:16:10
Guardado part-00015.parquet | filas=1,000 | duración=0.61 s | fin=04:16:10
Consultando lote 16 | offset=16,000 | limit=1,000 | inicio=04:16:10
Guardado part-00016.parquet | filas=1,000 | duración=0.62 s | fin=04:16:11
Consultando lote 17 | offset=17,000 | limit=1,000 | inicio=04:16:11
Guardado part-00017.parquet | filas=1,000 | duración=0.71 s | fin=04:16:12
Consultando lote 18 | offset=18,000 | limit=1,000 | inicio=04:16:12
Guardado part-00018.parquet | filas=1,000 | duración=0.62 s | fin=04:16:12
Consultando lote 19 | offset=19,000 | limit=1,000 | inicio=04:16:12
Guardado part-00019.parquet | filas=1,000 | duración=0.73 s | fin=04:16:13
Consultando lote 20 | offset=20,000 | limit=1,000 | inicio=04:16:13
Guardado part-00020.parquet | filas=1,000 | duración=0.64 s | fin=04:16:14
Consultando lote 21 | offset=21,000 | limit=1,000 | inicio=04:16:14
Guardado part-00021.parquet | filas=1,000 | duración=0.79 s | fin=04:16:15
Consultando lote 22 | offset=22,000 | limit=1,000 | inicio=04:16:15
Guardado part-00022.parquet | filas=1,000 | duración=0.79 s | fin=04:16:15
Consultando lote 23 | offset=23,000 | limit=1,000 | inicio=04:16:15
Guardado part-00023.parquet | filas=1,000 | duración=0.69 s | fin=04:16:16
Consultando lote 24 | offset=24,000 | limit=1,000 | inicio=04:16:16
Guardado part-00024.parquet | filas=1,000 | duración=0.84 s | fin=04:16:17
Consultando lote 25 | offset=25,000 | limit=1,000 | inicio=04:16:17
Guardado part-00025.parquet | filas=1,000 | duración=0.71 s | fin=04:16:18
Consultando lote 26 | offset=26,000 | limit=1,000 | inicio=04:16:18
Guardado part-00026.parquet | filas=1,000 | duración=0.88 s | fin=04:16:18
Consultando lote 27 | offset=27,000 | limit=1,000 | inicio=04:16:18
Guardado part-00027.parquet | filas=1,000 | duración=0.91 s | fin=04:16:19
Consultando lote 28 | offset=28,000 | limit=1,000 | inicio=04:16:19
Guardado part-00028.parquet | filas=1,000 | duración=0.85 s | fin=04:16:20
Consultando lote 29 | offset=29,000 | limit=1,000 | inicio=04:16:20
Guardado part-00029.parquet | filas=1,000 | duración=0.83 s | fin=04:16:21
Consultando lote 30 | offset=30,000 | limit=1,000 | inicio=04:16:21
Guardado part-00030.parquet | filas=1,000 | duración=0.81 s | fin=04:16:22
Consultando lote 31 | offset=31,000 | limit=1,000 | inicio=04:16:22
Guardado part-00031.parquet | filas=1,000 | duración=0.81 s | fin=04:16:23
Consultando lote 32 | offset=32,000 | limit=1,000 | inicio=04:16:23
Guardado part-00032.parquet | filas=1,000 | duración=0.92 s | fin=04:16:24
Consultando lote 33 | offset=33,000 | limit=1,000 | inicio=04:16:24
Guardado part-00033.parquet | filas=1,000 | duración=0.75 s | fin=04:16:24
Consultando lote 34 | offset=34,000 | limit=1,000 | inicio=04:16:24
Guardado part-00034.parquet | filas=1,000 | duración=0.86 s | fin=04:16:25
Consultando lote 35 | offset=35,000 | limit=1,000 | inicio=04:16:25
Guardado part-00035.parquet | filas=1,000 | duración=0.88 s | fin=04:16:26
Consultando lote 36 | offset=36,000 | limit=1,000 | inicio=04:16:26
Guardado part-00036.parquet | filas=1,000 | duración=0.88 s | fin=04:16:27
Consultando lote 37 | offset=37,000 | limit=1,000 | inicio=04:16:27
Guardado part-00037.parquet | filas=1,000 | duración=0.84 s | fin=04:16:28
Consultando lote 38 | offset=38,000 | limit=1,000 | inicio=04:16:28
Guardado part-00038.parquet | filas=1,000 | duración=0.83 s | fin=04:16:29
Consultando lote 39 | offset=39,000 | limit=1,000 | inicio=04:16:29
Guardado part-00039.parquet | filas=1,000 | duración=1.05 s | fin=04:16:30
Consultando lote 40 | offset=40,000 | limit=1,000 | inicio=04:16:30
Guardado part-00040.parquet | filas=1,000 | duración=1.09 s | fin=04:16:31
Consultando lote 41 | offset=41,000 | limit=1,000 | inicio=04:16:31
Guardado part-00041.parquet | filas=1,000 | duración=1.00 s | fin=04:16:32
Consultando lote 42 | offset=42,000 | limit=1,000 | inicio=04:16:32
Guardado part-00042.parquet | filas=1,000 | duración=0.99 s | fin=04:16:33
Consultando lote 43 | offset=43,000 | limit=1,000 | inicio=04:16:33
Guardado part-00043.parquet | filas=1,000 | duración=0.90 s | fin=04:16:34
Consultando lote 44 | offset=44,000 | limit=1,000 | inicio=04:16:34
Guardado part-00044.parquet | filas=1,000 | duración=1.01 s | fin=04:16:35
Consultando lote 45 | offset=45,000 | limit=1,000 | inicio=04:16:35
Guardado part-00045.parquet | filas=1,000 | duración=0.95 s | fin=04:16:36
Consultando lote 46 | offset=46,000 | limit=1,000 | inicio=04:16:36
Guardado part-00046.parquet | filas=1,000 | duración=0.99 s | fin=04:16:37
Consultando lote 47 | offset=47,000 | limit=1,000 | inicio=04:16:37
Guardado part-00047.parquet | filas=1,000 | duración=0.92 s | fin=04:16:38
Consultando lote 48 | offset=48,000 | limit=1,000 | inicio=04:16:38
Guardado part-00048.parquet | filas=1,000 | duración=0.96 s | fin=04:16:39
Consultando lote 49 | offset=49,000 | limit=1,000 | inicio=04:16:39
Guardado part-00049.parquet | filas=1,000 | duración=1.02 s | fin=04:16:40
Consultando lote 50 | offset=50,000 | limit=1,000 | inicio=04:16:40
Guardado part-00050.parquet | filas=1,000 | duración=1.13 s | fin=04:16:41
Consultando lote 51 | offset=51,000 | limit=1,000 | inicio=04:16:41
Guardado part-00051.parquet | filas=1,000 | duración=1.20 s | fin=04:16:42
Consultando lote 52 | offset=52,000 | limit=1,000 | inicio=04:16:42
Guardado part-00052.parquet | filas=1,000 | duración=1.04 s | fin=04:16:43
Consultando lote 53 | offset=53,000 | limit=1,000 | inicio=04:16:43
Guardado part-00053.parquet | filas=1,000 | duración=1.17 s | fin=04:16:44
Consultando lote 54 | offset=54,000 | limit=1,000 | inicio=04:16:44
Guardado part-00054.parquet | filas=1,000 | duración=0.99 s | fin=04:16:45
Consultando lote 55 | offset=55,000 | limit=1,000 | inicio=04:16:45
Guardado part-00055.parquet | filas=1,000 | duración=1.16 s | fin=04:16:46
Consultando lote 56 | offset=56,000 | limit=1,000 | inicio=04:16:46
Guardado part-00056.parquet | filas=1,000 | duración=1.10 s | fin=04:16:47
Consultando lote 57 | offset=57,000 | limit=1,000 | inicio=04:16:47
Guardado part-00057.parquet | filas=1,000 | duración=1.06 s | fin=04:16:48
Consultando lote 58 | offset=58,000 | limit=1,000 | inicio=04:16:48
Guardado part-00058.parquet | filas=1,000 | duración=1.11 s | fin=04:16:50
Consultando lote 59 | offset=59,000 | limit=1,000 | inicio=04:16:50
Guardado part-00059.parquet | filas=1,000 | duración=1.14 s | fin=04:16:51
Consultando lote 60 | offset=60,000 | limit=1,000 | inicio=04:16:51
Guardado part-00060.parquet | filas=1,000 | duración=1.04 s | fin=04:16:52
Consultando lote 61 | offset=61,000 | limit=1,000 | inicio=04:16:52
Guardado part-00061.parquet | filas=1,000 | duración=1.06 s | fin=04:16:53
Consultando lote 62 | offset=62,000 | limit=1,000 | inicio=04:16:53
Guardado part-00062.parquet | filas=1,000 | duración=1.09 s | fin=04:16:54
Consultando lote 63 | offset=63,000 | limit=1,000 | inicio=04:16:54
Guardado part-00063.parquet | filas=1,000 | duración=1.19 s | fin=04:16:55
Consultando lote 64 | offset=64,000 | limit=1,000 | inicio=04:16:55
Guardado part-00064.parquet | filas=1,000 | duración=1.21 s | fin=04:16:56
Consultando lote 65 | offset=65,000 | limit=1,000 | inicio=04:16:56
Guardado part-00065.parquet | filas=1,000 | duración=1.21 s | fin=04:16:57
Consultando lote 66 | offset=66,000 | limit=1,000 | inicio=04:16:57
Guardado part-00066.parquet | filas=1,000 | duración=1.25 s | fin=04:16:59
Consultando lote 67 | offset=67,000 | limit=1,000 | inicio=04:16:59
Guardado part-00067.parquet | filas=1,000 | duración=1.48 s | fin=04:17:00
Consultando lote 68 | offset=68,000 | limit=1,000 | inicio=04:17:00
Guardado part-00068.parquet | filas=1,000 | duración=1.10 s | fin=04:17:01
Consultando lote 69 | offset=69,000 | limit=1,000 | inicio=04:17:01
Guardado part-00069.parquet | filas=1,000 | duración=1.41 s | fin=04:17:03
Consultando lote 70 | offset=70,000 | limit=1,000 | inicio=04:17:03
Guardado part-00070.parquet | filas=1,000 | duración=1.24 s | fin=04:17:04
Consultando lote 71 | offset=71,000 | limit=1,000 | inicio=04:17:04
Guardado part-00071.parquet | filas=1,000 | duración=1.28 s | fin=04:17:05
Consultando lote 72 | offset=72,000 | limit=1,000 | inicio=04:17:05
Guardado part-00072.parquet | filas=884 | duración=1.19 s | fin=04:17:06
Último lote detectado con 884 filas.

---

## Resumen final

,dataset_id,variable,departamento,anio,mes,estado,partes_existentes_inicio,partes_escritas_corrida,filas_corrida,duracion_segundos,carpeta
0,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,1,completa,0,36,35811,22.17,/content/drive/MyDrive/eco2026_processed/clima...
1,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,2,completa,0,22,21924,13.95,/content/drive/MyDrive/eco2026_processed/clima...
2,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,3,completa,0,20,19670,11.62,/content/drive/MyDrive/eco2026_processed/clima...
3,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,4,completa,0,16,15830,12.99,/content/drive/MyDrive/eco2026_processed/clima...
4,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,5,completa,0,20,19410,12.64,/content/drive/MyDrive/eco2026_processed/clima...
5,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,6,completa,0,22,21983,13.48,/content/drive/MyDrive/eco2026_processed/clima...
6,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,7,completa,0,24,23966,16.45,/content/drive/MyDrive/eco2026_processed/clima...
7,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,8,completa,0,43,42574,28.53,/content/drive/MyDrive/eco2026_processed/clima...
8,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,9,completa,0,33,32053,20.84,/content/drive/MyDrive/eco2026_processed/clima...
9,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,10,completa,0,66,65417,50.66,/content/drive/MyDrive/eco2026_processed/clima...
10,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,11,completa,0,72,71788,65.54,/content/drive/MyDrive/eco2026_processed/clima...
11,62tk-nxj5,presion_atmosferica,CUNDINAMARCA,2024,12,completa,0,73,72884,66.58,/content/drive/MyDrive/eco2026_processed/clima...

,departamento,anio,mes,lote,offset,filas,estado,inicio,fin,duracion_segundos,archivo
0,CUNDINAMARCA,2024,1,0,0,1000,escrito,2026-07-13T04:11:31,2026-07-13T04:11:31,0.62,/content/drive/MyDrive/eco2026_processed/clima...
1,CUNDINAMARCA,2024,1,1,1000,1000,escrito,2026-07-13T04:11:31,2026-07-13T04:11:32,0.55,/content/drive/MyDrive/eco2026_processed/clima...
2,CUNDINAMARCA,2024,1,2,2000,1000,escrito,2026-07-13T04:11:32,2026-07-13T04:11:32,0.53,/content/drive/MyDrive/eco2026_processed/clima...
3,CUNDINAMARCA,2024,1,3,3000,1000,escrito,2026-07-13T04:11:32,2026-07-13T04:11:33,0.62,/content/drive/MyDrive/eco2026_processed/clima...
4,CUNDINAMARCA,2024,1,4,4000,1000,escrito,2026-07-13T04:11:33,2026-07-13T04:11:34,0.47,/content/drive/MyDrive/eco2026_processed/clima...
...,...,...,...,...,...,...,...,...,...,...,...
442,CUNDINAMARCA,2024,12,68,68000,1000,escrito,2026-07-13T04:17:00,2026-07-13T04:17:01,1.10,/content/drive/MyDrive/eco2026_processed/clima...
443,CUNDINAMARCA,2024,12,69,69000,1000,escrito,2026-07-13T04:17:01,2026-07-13T04:17:03,1.41,/content/drive/MyDrive/eco2026_processed/clima...
444,CUNDINAMARCA,2024,12,70,70000,1000,escrito,2026-07-13T04:17:03,2026-07-13T04:17:04,1.24,/content/drive/MyDrive/eco2026_processed/clima...
445,CUNDINAMARCA,2024,12,71,71000,1000,escrito,2026-07-13T04:17:04,2026-07-13T04:17:05,1.28,/content/drive/MyDrive/eco2026_processed/clima...
446,CUNDINAMARCA,2024,12,72,72000,884,escrito,2026-07-13T04:17:05,2026-07-13T04:17:06,1.19,/content/drive/MyDrive/eco2026_processed/clima...

In [6]:
from pathlib import Path

def obtener_tamano_carpeta(ruta_carpeta):
    total_bytes = 0
    for archivo in ruta_carpeta.glob('*.parquet'):
        total_bytes += archivo.stat().st_size
    return total_bytes

# Filtrar el resumen de particiones para el año 2024
resumen_2024 = resumen_particiones[resumen_particiones['anio'] == 2024]

total_tamano_bytes = 0
for index, row in resumen_2024.iterrows():
    carpeta_path = Path(row['carpeta'])
    total_tamano_bytes += obtener_tamano_carpeta(carpeta_path)

# Convertir a un formato legible (MB, GB)
total_tamano_mb = total_tamano_bytes / (1024 * 1024)
total_tamano_gb = total_tamano_bytes / (1024 * 1024 * 1024)

print(f"El tamaño total de la descarga para el año 2024 es:")
print(f"- {total_tamano_bytes:,} bytes")
print(f"- {total_tamano_mb:.2f} MB")
print(f"- {total_tamano_gb:.2f} GB")

El tamaño total de la descarga para el año 2024 es:
- 8,242,920 bytes
- 7.86 MB
- 0.01 GB

## 6. Qué queda pendiente

La salida conserva observaciones crudas normalizadas y trazabilidad de la fuente. Las siguientes tareas deben desarrollarse por variable y fuera de este notebook:

- Revisar duplicados por estación, sensor y fecha.
- Medir frecuencia y cobertura temporal por estación.
- Definir reglas de valores físicamente plausibles.
- Construir agregados diarios y por periodo agrícola.
- Decidir cómo combinar estaciones dentro de un municipio.

No use una suma genérica para temperatura, humedad, presión o viento.